config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :smart_contracts, only: %i[index new edit]
  get "about" => 'application#about'

  root 'smart_contracts#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/smart_contract.rb
# frozen_string_literal: true

class SmartContract < ApplicationRecord
  attr_accessor :enabled, :smart_contract_address, :chain, :azero_id, :group_id, :abi_url, :contract_url, :wasm_url, :audit_url, :github, :project_name, :project_website

  # === ACTIVE STORAGE ===
  has_one_attached :abi
  has_one_attached :contract
  has_one_attached :wasm
  has_one_attached :audit

  # === VALIDATIONS ===
  # ACTIVE STORAGE
  validates :abi, attached: true, content_type: :json, size: { less_than: 500.kilobyte }
  # octet_stream is the content_type of a .contract file
  validates :contract, content_type: :octet_stream, size: { less_than: 500.kilobyte }
  validates :wasm, content_type: :wasm, size: { less_than: 500.kilobyte }
  validates :audit, content_type: :pdf, size: { less_than: 2.megabytes }
end

app/controllers/active_storage/direct_uploads_controller.rb
# frozen_string_literal: true

# Creates a new blob on the server side in anticipation of a direct-to-service upload from the client side.
# When the client-side upload is completed, the signed_blob_id can be submitted as part of the form to reference
# the blob that was created up front.

# 22/SEP/2023 - Monkey patching this so that file extensions are used for keys
# May not even need to use active storage
module ActiveStorage
  class DirectUploadsController < ActiveStorage::BaseController
    def create
      blob = ActiveStorage::Blob.create_before_direct_upload!(**blob_args.merge(key: "#{ActiveStorage::Blob.generate_unique_secure_token(length: ActiveStorage::Blob::MINIMUM_TOKEN_LENGTH)}.#{blob_args[:filename].split('.').last}"))
      render json: direct_upload_json(blob)
    end

    private

      def blob_args
        params.require(:blob).permit(:filename, :byte_size, :checksum, :content_type, metadata: {}).to_h.symbolize_keys
      end

      def direct_upload_json(blob)
        blob.as_json(root: false, methods: :signed_id).merge(direct_upload: {
                                                               url: blob.service_url_for_direct_upload,
                                                               headers: blob.service_headers_for_direct_upload
                                                             })
      end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/metadata_controller.rb
# frozen_string_literal: true

class MetadataController < ApplicationController
  def index; end

  def new; end
end

app/controllers/smart_contracts_controller.rb
# frozen_string_literal: true

class SmartContractsController < ApplicationController
  def index; end

  def new; end

  def edit; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/metadata_helper.rb
# frozen_string_literal: true

module MetadataHelper
end

app/helpers/smart_contracts_helper.rb
# frozen_string_literal: true

module SmartContractsHelper
end

app/views/application/_button_loading.html.haml
:ruby
  button_type ||= 'button'
  data ||= nil
  ready_label ||= nil
  icon_only ||= false
  button_id ||= nil

= render 'loading', tag_type: button_type, data:, ready_label:, icon_only:, tag_classes: button_classes, tag_id: button_id do
  = ready_label || yield

app/views/application/_footer.html.haml
%footer.footer.d-flex.align-items-center
  .container-fluid
    .row
      .col-12.d-flex.justify-content-between
        = link_to 'https://btn.group', target: '_blank', rel: 'noopener' do
          = image_tag 'https://res.cloudinary.com/hv5cxagki/image/upload/c_scale,dpr_2,f_auto,h_30,q_auto/v1/branding/black-with-text_jrkb7u_i1xuow_ii0vtw.png', class: 'logo logo-dark'
          = image_tag 'https://res.cloudinary.com/hv5cxagki/image/upload/c_scale,dpr_2,f_auto,h_30,q_auto/v1/branding/logo_plus_text_1_fitfuq_uqsgxw.png', class: 'logo logo-light'
        .text-end
          = link_to 'https://alephzero.org/ecosystem-funding-program', target: '_blank', rel: 'noopener' do
            = image_tag 'https://res.cloudinary.com/hv5cxagki/image/upload/v1698832330/logos/aleph-zero-efp.a76d0a07_xvnkap.svg', class: 'logo logo-dark'
            = image_tag 'az-efp-light.svg', class: 'logo logo-light'

app/views/application/_header.html.haml
%header#page-topbar
  .layout-width
    .navbar-header
      .d-flex
        .horizontal-logo
          = link_to root_path, class: 'logo logo-dark' do
            %span.logo-sm
              / %img{alt: "", height: "22", src: "assets/images/logo-sm.png"}/
              .fs-5.text-white Smart Contract Hub
            %span.logo-lg
              / %img{alt: "", height: "17", src: "assets/images/logo-dark.png"}/
              .fs-2.text-white Smart Contract Hub
          = link_to root_path, class: 'logo logo-light' do
            %span.logo-sm
              / %img{alt: "", height: "22", src: "assets/images/logo-sm.png"}/
              .fs-5.text-white Smart Contract Hub
            %span.logo-lg
              / %img{alt: "", height: "17", src: "assets/images/logo-light.png"}/
              .fs-2.text-white Smart Contract Hub
        .header-item
          = link_to 'https://btn-group.gitbook.io/smart-contract-hub/', target: '_blank', rel: 'noopener' do
            %button.btn.btn-icon.btn-topbar.btn-ghost-secondary.rounded-circle.light-dark-mode{ type: 'button' }
              %i.bx.bx-info-circle.fs-22
      .d-flex.align-items-center
        .header-item
          %button.btn.btn-icon.btn-topbar.btn-ghost-secondary.rounded-circle.light-dark-mode{ type: 'button' }
            %i.bx.bx-moon.fs-22
        .dropdown.ms-sm-3.header-item.topbar-user
          %button.btn.d-none#page-header-user-dropdown{ 'aria-expanded' => 'false', 'aria-haspopup' => 'true', 'data-bs-toggle' => 'dropdown', type: 'button', 'data-bs-auto-close': 'outside' }
            %span.d-flex.align-items-center
              %img.user-address-alias-avatar{ alt: 'Wallet logo', src: 'https://www.pngall.com/wp-content/uploads/12/Avatar-Profile-PNG-Clipart.png', height: 40 }
              .text-start.ms-3
                .fw-medium.user-name-text.account-name
                .fs-12.user-name-sub-text.account-address-abbreviated
          .dropdown-menu.dropdown-menu-end
            %h6.dropdown-header
              .d-flex.flex-column.position-relative
                .d-flex.align-items-center
                  .wallet-address.me-2#polkadot-user-account-menu-wallet-address
                  %button.btn.btn-icon.btn-sm
                    %i.bi.bi-clipboard.text-muted.fs-4{ 'data-clipboard-target' => '#polkadot-user-account-menu-wallet-address' }
            .dropdown-divider
            = link_to 'Change', '#', id: 'change-account-link', class: 'dropdown-item'
        = render 'polkadot_connect_button'

app/views/application/_loading.html.haml
:ruby
  tag_type ||= nil
  data ||= nil
  ready_label ||= nil
  icon_only ||= false
  tag_classes ||= nil
  tag_id ||= nil
  tag_name ||= :button

= content_tag tag_name, type: tag_type, class: tag_classes, data:, id: tag_id do
  %span.d-none.loading
    %em.spinner-grow.spinner-grow-sm{ 'aria-hidden' => 'true', role: 'status' }
    - unless icon_only
      %em.loading-status Loading...
  %span.ready
    = ready_label || yield

app/views/application/_polkadot_account_list.html.haml
.modal.fade#polkadot-account-list{ 'aria-hidden' => 'true', role: 'dialog', tabindex: '-1' }
  .modal-dialog
    .modal-content
      .modal-header
        %h5.modal-title Select an account
        %button.btn-close{ 'aria-label' => 'Close', 'data-bs-dismiss' => 'modal', type: 'button' }
      .modal-body
        .list-group.overflow-auto

app/views/application/_polkadot_connect_button.html.haml
- extra_button_classes ||= 'btn-primary'

= render 'button_loading', button_classes: "btn d-none polkadot-connect-button #{extra_button_classes}" do
  Connect Wallet

app/views/application/_preloader.html.haml
#preloader
  #status
    .spinner-border.text-primary.avatar-sm{ role: 'status' }
      %span.visually-hidden Loading...

app/views/layouts/application.html.haml
!!!
%html{ 'data-bs-theme' => 'light', 'data-layout' => 'horizontal', 'data-preloader' => 'enable', 'data-sidebar' => 'light', 'data-sidebar-image' => 'none', 'data-sidebar-size' => 'lg', 'data-topbar' => 'dark', lang: 'en' }
  %head
    %title Smart Contract Hub
    %meta{ charset: 'utf-8' }
    = favicon_link_tag 'favicon.png'
    %meta{ name: 'description', content: 'Smart contract hub for Aleph Zero.' }
    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no' }
    %meta{ property: 'og:image', content: 'https://res.cloudinary.com/hv5cxagki/image/upload/v1700602952/logos/favicon_in_between_padding_dg462h.png' }
    %meta{ property: 'og:site_name', content: 'Smart Contract Hub' }
    = csrf_meta_tags
    = csp_meta_tag

    // === CUSTOM ===
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload'

    // === DATATABLE ===
    %link{ href: 'https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css', rel: 'stylesheet' }
    %script{ src: 'https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.js' }
    %script{ src: 'https://cdn.datatables.net/plug-ins/1.13.6/api/processing().js', type: 'text/javascript' }
    // === CLIPBOARD ===
    %script{ src: 'https://cdn.jsdelivr.net/npm/clipboard@2.0.11/dist/clipboard.min.js' }
  %body{ class: "rails-env-#{Rails.env}" }
    #layout-wrapper
      = render 'header'
      .main-content
        .page-content
          = yield
      = render 'footer'
    = render 'preloader'
    = render 'polkadot_account_list'

app/views/metadata/new.html.haml
.container.mt-5.polkadotjs#metadata-new
  .row
    .col-md-9.mx-auto.mb-5
      .card
        .card-body
          %h1 New metadata
          %form{ name: 'newForm' }
            .mb-3
              %label.form-label{ for: 'smart-contract-address-input' } Smart contract address
              %input.form-control#smart-contract-address-input{ name: 'smartContractAddress', required: true }
            .mb-3
              %button.btn.btn-primary.btn-sm{ type: 'button' } Upload metadata.json
              %input.d-none{ name: 'url' }
            = render 'button_loading', button_classes: 'btn btn-primary', button_type: 'submit', ready_label: 'Create'

app/views/smart_contracts/edit.html.haml
.container.polkadotjs#smart-contracts-edit
  .row
    .col-md-9.mx-auto.mb-5
      .card
        .card-body
          %h1 Edit smart contract
          = form_for SmartContract.new, multipart: true, html: { name: 'smartContractEditForm' } do |f|
            .mb-3
              = f.label :id, class: 'form-label required'
              = f.text_field :id, class: 'form-control', required: true, disabled: true, value: params[:id]
            .mb-3
              = f.label :smart_contract_address, class: 'form-label required'
              = f.text_field :smart_contract_address, class: 'form-control', required: true, disabled: true
            .mb-3
              = f.label :project_name, class: 'form-label'
              = f.text_field :project_name, class: 'form-control'
            .mb-3
              = f.label :project_website, class: 'form-label'
              = f.text_field :project_website, class: 'form-control'
            .mb-3
              = f.label :github, class: 'form-label'
              = f.text_field :github, class: 'form-control'
            .mb-3
              .label-with-hint-container
                = f.label :azero_id, 'Your AZERO.ID', class: 'form-label required'
                %i.ms-2.ri-question-line{ tabindex: '-1', 'data-bs-trigger': 'focus', 'data-bs-html': 'true', 'data-bs-container': 'body', 'data-bs-toggle': 'popover', 'data-bs-placement' => 'top', 'data-bs-container' => 'body', 'data-bs-content': 'Associating an AZERO.ID is mandatory. It will: <ul class="ps-3"><li>enable finding by AZERO.ID.</li><li>increase trustability by making it easier to identify the creator.</li></ul>An AZERO.ID can be created <a href="https://azero.id/" target="_blank" rel="noopener">here</a>.' }
              = f.select :azero_id, [], { include_blank: false }, { class: 'form-select' }
            .mb-3
              .label-with-hint-container
                = f.label :group_id, 'Your Group', class: 'form-label'
                %i.ms-2.ri-question-line{ tabindex: '-1', 'data-bs-trigger': 'focus', 'data-bs-html': 'true', 'data-bs-container': 'body', 'data-bs-toggle': 'popover', 'data-bs-placement' => 'top', 'data-bs-container' => 'body', 'data-bs-content': 'Associating a group will: <ul class="ps-3"><li>enable finding by group.</li><li>increase trustability.</li></ul>Groups can be created <a href="https://btn.group/aleph_zero/groups" target="_blank" rel="noopener">here</a>.' }
              = f.select :group_id, [], { include_blank: true }, { class: 'form-select' }
            .row.mb-3
              .col-6.col-lg-3
                = f.label :audit, class: 'form-label'
                = f.file_field :audit, direct_upload: true, hidden: true, disabled: true
                .dropzone#audit-dropzone
                  .dz-message.needsclick
                    .mb-3
                      %i.display-4.text-muted.ri-upload-cloud-2-fill
                    .text-muted Drop .pdf file here or click to upload.
                = f.text_field :audit_url, hidden: true
            .mb-3
              = f.check_box :enabled
              = f.label :enabled, class: 'form-label'
            .d-flex.mt-3
              = link_to 'Cancel', root_path, class: 'btn btn-light me-3'
              = render 'button_loading', button_classes: 'btn btn-primary', button_type: 'submit', ready_label: 'Update'
        .card-footer
          .card-text
            %small.text-muted The smart contract address, chain, ABI, contract file and WASM can not be changed. If any of these fields are incorrect, please disable this record and create a new one.

app/views/smart_contracts/index.html.haml
.container-fluid.polkadotjs#smart-contracts-index
  .row
    .col-12
      .card
        .card-header.border-0
          .d-flex.align-items-center
            %h5.card-title.mb-0.flex-grow-1 Smart Contracts
            .flex-shrink-0
              .d-flex.flex-wrap.gap-2
                = link_to new_smart_contract_path, class: 'btn btn-primary add-btn' do
                  %i.ri-add-line.align-bottom.me-1
                  New
        .card-body.border.border-dashed.border-end-0.border-start-0
          .row.g-3
            .col-xxl-6.col-sm-12
              %form.validation-required
                .search-box
                  %input.form-control.search.bg-light.border-light#search-input{ placeholder: 'Search ...', type: 'text', autocomplete: 'off', value: params[:search] }
                  %i.ri-search-line.search-icon
                .invalid-feedback
                  Invalid address.
            .col-xxl-3.col-sm-4
              %select.form-select#search-by-select
                - [{ value: 'nil', label: 'Search by' }, { value: 'id', label: 'ID' }, { value: 'project/address', label: 'Project / Smart Contract' }, { value: 'addedBy', label: 'Added By Address' }, { value: 'groupName', label: 'Added By Group' }, { value: 'azeroId', label: 'Added By AZERO.ID' }].each do |option_details|
                  %option{ disabled: option_details[:value] == 'nil', value: option_details[:value], selected: params[:search_by] == option_details[:value] || (option_details[:value] == 'project/address' && params[:search_by].blank?) }= option_details[:label]
            .col-xxl-3.col-sm-4
              %select.form-select#status-select
                - [{ value: 'nil', label: 'Status' }, { value: 'all', label: 'All' }, { value: 'enabled', label: 'Enabled' }, { value: 'disabled', label: 'Disabled' }].each do |option_details|
                  %option{ disabled: option_details[:value] == 'nil', value: option_details[:value], selected: params[:enabled] == option_details[:value] || (option_details[:value] == 'enabled' && params[:enabled].blank?) }= option_details[:label]
        .card-body
          .table-responsive.table-card.mb-4
            %table.table.align-middle.table-nowrap.mb-0#smart-contracts-table

app/views/smart_contracts/new.html.haml
.container.polkadotjs#smart-contracts-new
  .row
    .col-md-9.mx-auto.mb-5
      .card
        .card-body
          %h1 New smart contract
          = form_for SmartContract.new, multipart: true, html: { name: 'smartContractNewForm', novalidate: '', class: 'needs-validation' } do |f|
            .mb-3
              = f.label :smart_contract_address, class: 'form-label required'
              = f.text_field :smart_contract_address, class: 'form-control', required: ''
              .invalid-feedback
                Invalid address.
            .mb-3
              = f.label :chain, class: 'form-label required'
              = f.select :chain, [['Mainnet', 0], ['Testnet', 1]], { include_blank: false }, { class: 'form-select' }
            .mb-3
              = f.label :project_name, class: 'form-label'
              = f.text_field :project_name, class: 'form-control'
            .mb-3
              = f.label :project_website, class: 'form-label'
              = f.text_field :project_website, class: 'form-control'
            .mb-3
              = f.label :github, class: 'form-label'
              = f.text_field :github, class: 'form-control'
            .mb-3
              .label-with-hint-container
                = f.label :azero_id, 'Your AZERO.ID', class: 'form-label required'
                %i.ms-2.ri-question-line{ tabindex: '-1', 'data-bs-trigger': 'focus', 'data-bs-html': 'true', 'data-bs-container': 'body', 'data-bs-toggle': 'popover', 'data-bs-placement' => 'top', 'data-bs-container' => 'body', 'data-bs-content': 'Associating an AZERO.ID is mandatory. It will: <ul class="ps-3"><li>enable finding by AZERO.ID.</li><li>increase trustability by making it easier to identify the creator.</li></ul>An AZERO.ID can be created <a href="https://azero.id/" target="_blank" rel="noopener">here</a>.' }
              = f.select :azero_id, [], { include_blank: false }, { class: 'form-select' }
            .mb-3
              .label-with-hint-container
                = f.label :group_id, 'Your Group', class: 'form-label'
                %i.ms-2.ri-question-line{ tabindex: '-1', 'data-bs-trigger': 'focus', 'data-bs-html': 'true', 'data-bs-container': 'body', 'data-bs-toggle': 'popover', 'data-bs-placement' => 'top', 'data-bs-container' => 'body', 'data-bs-content': 'Associating a group will: <ul class="ps-3"><li>enable finding by group.</li><li>increase trustability.</li></ul>Groups can be created <a href="https://btn.group/aleph_zero/groups" target="_blank" rel="noopener">here</a>.' }
              = f.select :group_id, [], { include_blank: true }, { class: 'form-select' }
            .row.mb-3
              .col-6.col-lg-3.mb-3
                = f.label :abi, class: 'form-label required'
                = f.file_field :abi, direct_upload: true, hidden: true, disabled: true
                .dropzone#abi-dropzone
                  .dz-message.needsclick
                    .mb-3
                      %i.display-4.text-muted.ri-upload-cloud-2-fill
                    .text-muted Drop .json file here or click to upload.
                = f.text_field :abi_url, hidden: true, required: true
                .invalid-feedback
                  File required.
              .col-6.col-lg-3.mb-3
                = f.label :contract, class: 'form-label'
                = f.file_field :contract, direct_upload: true, hidden: true, disabled: true
                .dropzone#contract-dropzone
                  .dz-message.needsclick
                    .mb-3
                      %i.display-4.text-muted.ri-upload-cloud-2-fill
                    .text-muted Drop .contract file here or click to upload.
                = f.text_field :contract_url, hidden: true
              .col-6.col-lg-3
                = f.label :wasm, class: 'form-label'
                = f.file_field :wasm, direct_upload: true, hidden: true, disabled: true
                .dropzone#wasm-dropzone
                  .dz-message.needsclick
                    .mb-3
                      %i.display-4.text-muted.ri-upload-cloud-2-fill
                    .text-muted Drop .wasm file here or click to upload.
                = f.text_field :wasm_url, hidden: true
              .col-6.col-lg-3
                = f.label :audit, class: 'form-label'
                = f.file_field :audit, direct_upload: true, hidden: true, disabled: true
                .dropzone#audit-dropzone
                  .dz-message.needsclick
                    .mb-3
                      %i.display-4.text-muted.ri-upload-cloud-2-fill
                    .text-muted Drop .pdf file here or click to upload.
                = f.text_field :audit_url, hidden: true
            .d-flex.mt-3
              = link_to 'Cancel', root_path, class: 'btn btn-light me-3'
              = render 'button_loading', button_classes: 'btn btn-primary', button_type: 'submit', ready_label: 'Create'
        .card-footer
          .card-text
            %small.text-muted
              %ul
                %li The smart contract address, chain, ABI, contract file and WASM can not be changed later on.